---
- name: Apply OS hardening
  hosts: all
  become: yes
  # vars:
  #   # Network security
  #   network_ipv6_enable: false
  #   network_forwarding: false
    
  #   # File system security
  #   os_selinux_state: enforcing
  #   hidepid_option: 2
    
  #   # Kernel security
  #   enable_module_loading: false
  #   sysctl_params:
  #     net.ipv4.conf.all.send_redirects: 0
  #     net.ipv4.conf.default.send_redirects: 0
  #     net.ipv4.tcp_syncookies: 1
    
  #   # User security
  #   passwd_max_days: 90
  #   passwd_min_days: 7
  #   passwd_warn_age: 7
  roles:
    - { role: roles/os-hardening, become: true, tags: harden-os}