---
- name: Install and configure nginx
  hosts: webservers
  become: yes
  # vars:
  #   nginx_vhosts:
  #     - listen: "80"
  #       server_name: "example.com www.example.com"
  #       return: "301 https://$server_name$request_uri"
  #     - listen: "443 ssl"
  #       server_name: "example.com www.example.com"
  #       root: "/var/www/html"
  #       index: "index.php index.html index.htm"
  #       template: "vhost.conf.j2"  # Your custom template
  #       ssl_certificate: "/etc/ssl/certs/example.com.crt"
  #       ssl_certificate_key: "/etc/ssl/private/example.com.key"
    
  #   # Basic nginx configuration
  #   nginx_remove_default_vhost: true
  #   nginx_worker_connections: "1024"
    
  #   # SSL configuration (if using SSL)
  #   nginx_ssl_protocols: "TLSv1.2 TLSv1.3"
  #   nginx_ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256"
    
  roles:
    - { role: roles/nginx, become: true, tags: nginx-setup}