---
- hosts: my-servers
  become: true
  gather_facts: yes
  name: Hardening and Tuning os
  roles:
    #preparing server and hardening
    - { role: roles/preparing-server, become: True, tags: preparing-server}