all:
  children:
    other-servers:
      vars:
        ansible_user: "{{ server_user }}"
        ansible_port: "{{ server_port }}"
      hosts:
        web-servers:
          ansible_host: "{{ server_ip }}"
