---
- name: Update package database (FreeBSD)
  pkgng:
    update_cache: yes

- name: Upgrade all packages (FreeBSD)
  pkgng:
    name: "*"
    state: latest

- name: Install basic packages (FreeBSD)
  pkgng:
    name:
      - curl
      - wget
      - vim
      - htop
      - git
      - bash-completion
      - tree
      - sudo
      - security/ca_root_nss
    state: present