---
- name: Update apt cache (Ubuntu)
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages (Ubuntu)
  apt:
    upgrade: dist
    autoremove: yes

- name: Install basic packages (Ubuntu)
  apt:
    name:
      - curl
      - wget
      - vim
      - htop
      - git
      - bash-completion
      - tree
      - net-tools
      - sudo
      - ufw
      - software-properties-common
    state: present