#SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: Younes Modaresian
  description: Install Docker on multiple Linux/BSD distributions
  # company: your-company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Archlinux
      versions:
        - all
    - name: FreeBSD
      versions:
        - all
    - name: OpenBSD
      versions:
        - all
  galaxy_tags:
    - docker
    - container
    - multi-platform

dependencies: []